# This is a basic workflow to help you get started with Actions

name: Update README

# Controls when the workflow will run
on:
 schedule:
    - cron: '*/30 * * * *'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: carlysandler/github-activity-readme@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
